-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  name character varying NOT NULL,
  phone character varying NOT NULL UNIQUE,
  email character varying,
  birthday date,
  loyalty_points integer DEFAULT 0,
  total_visits integer DEFAULT 0,
  total_spent numeric DEFAULT 0,
  last_visit timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);
CREATE TABLE public.complaint_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  name character varying NOT NULL,
  display_name character varying NOT NULL,
  description text,
  emoji character varying,
  severity_default character varying DEFAULT 'medium'::character varying,
  auto_escalate boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT complaint_categories_pkey PRIMARY KEY (id),
  CONSTRAINT complaint_categories_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);
CREATE TABLE public.complaint_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  feedback_response_id uuid,
  salon_id uuid,
  client_id uuid,
  visit_id uuid,
  staff_id uuid,
  complaint_category character varying NOT NULL,
  complaint_text text,
  severity character varying DEFAULT 'medium'::character varying,
  status character varying DEFAULT 'pending'::character varying,
  resolution_notes text,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT complaint_reports_pkey PRIMARY KEY (id),
  CONSTRAINT complaint_reports_feedback_response_id_fkey FOREIGN KEY (feedback_response_id) REFERENCES public.feedback_responses(id),
  CONSTRAINT complaint_reports_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT complaint_reports_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT complaint_reports_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT complaint_reports_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id),
  CONSTRAINT complaint_reports_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.staff(id)
);
CREATE TABLE public.cs_tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  client_id uuid,
  scheduled_message_id uuid,
  task_type character varying NOT NULL,
  priority character varying DEFAULT 'normal'::character varying,
  status character varying DEFAULT 'pending'::character varying,
  title character varying NOT NULL,
  description text,
  assigned_to uuid,
  due_date date,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cs_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT cs_tasks_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT cs_tasks_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT cs_tasks_scheduled_message_id_fkey FOREIGN KEY (scheduled_message_id) REFERENCES public.scheduled_messages(id),
  CONSTRAINT cs_tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.staff(id)
);
CREATE TABLE public.engage_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid UNIQUE,
  feedback_enabled boolean DEFAULT true,
  feedback_delay_hours integer DEFAULT 9,
  auto_recovery_enabled boolean DEFAULT true,
  manager_alert_threshold integer DEFAULT 3,
  referral_reward_points integer DEFAULT 500,
  referral_tracking_enabled boolean DEFAULT true,
  staff_performance_tracking boolean DEFAULT true,
  whatsapp_feedback_enabled boolean DEFAULT true,
  sms_feedback_fallback boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT engage_settings_pkey PRIMARY KEY (id),
  CONSTRAINT engage_settings_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);
CREATE TABLE public.feedback_responses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  client_id uuid,
  visit_id uuid,
  staff_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  would_recommend boolean,
  feedback_channel character varying DEFAULT 'whatsapp'::character varying,
  responded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feedback_responses_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_responses_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT feedback_responses_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT feedback_responses_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT feedback_responses_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id)
);
CREATE TABLE public.loyalty_tiers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  name character varying NOT NULL,
  points_required integer NOT NULL,
  reward_description text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_tiers_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_tiers_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);
CREATE TABLE public.message_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  name character varying NOT NULL,
  display_name character varying NOT NULL,
  template text NOT NULL,
  trigger_type character varying NOT NULL,
  trigger_delay_days integer DEFAULT 0,
  service_category character varying,
  is_active boolean DEFAULT true,
  send_time time without time zone DEFAULT '10:00:00'::time without time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT message_templates_pkey PRIMARY KEY (id),
  CONSTRAINT message_templates_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);
CREATE TABLE public.recovery_actions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  client_id uuid,
  visit_id uuid,
  feedback_response_id uuid,
  complaint_report_id uuid,
  action_type character varying NOT NULL,
  action_taken_by uuid,
  offer_type character varying,
  offer_amount numeric,
  offer_code character varying,
  offer_expires date,
  customer_response text,
  outcome character varying,
  customer_returned boolean DEFAULT false,
  return_visit_id uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT recovery_actions_pkey PRIMARY KEY (id),
  CONSTRAINT recovery_actions_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT recovery_actions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT recovery_actions_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT recovery_actions_feedback_response_id_fkey FOREIGN KEY (feedback_response_id) REFERENCES public.feedback_responses(id),
  CONSTRAINT recovery_actions_complaint_report_id_fkey FOREIGN KEY (complaint_report_id) REFERENCES public.complaint_reports(id),
  CONSTRAINT recovery_actions_action_taken_by_fkey FOREIGN KEY (action_taken_by) REFERENCES public.staff(id),
  CONSTRAINT recovery_actions_return_visit_id_fkey FOREIGN KEY (return_visit_id) REFERENCES public.visits(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  referrer_id uuid,
  referred_client_id uuid,
  referral_source character varying DEFAULT 'word_of_mouth'::character varying,
  referrer_phone character varying,
  referrer_name character varying,
  status character varying DEFAULT 'pending'::character varying,
  first_visit_id uuid,
  reward_points integer DEFAULT 500,
  rewarded_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.clients(id),
  CONSTRAINT referrals_referred_client_id_fkey FOREIGN KEY (referred_client_id) REFERENCES public.clients(id),
  CONSTRAINT referrals_first_visit_id_fkey FOREIGN KEY (first_visit_id) REFERENCES public.visits(id)
);
CREATE TABLE public.salons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  phone character varying NOT NULL,
  email character varying,
  address text,
  city character varying,
  logo_url text,
  loyalty_points_per_ugx integer DEFAULT 1,
  loyalty_threshold integer DEFAULT 1000,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  subdomain character varying UNIQUE,
  custom_domain character varying,
  theme_primary_color character varying DEFAULT '#2563EB'::character varying,
  theme_secondary_color character varying DEFAULT '#F59E0B'::character varying,
  is_active boolean DEFAULT true,
  subscription_plan character varying DEFAULT 'trial'::character varying,
  subscription_expires_at timestamp with time zone,
  slogan character varying,
  whatsapp_phone_number_id character varying,
  whatsapp_phone_number character varying,
  whatsapp_status character varying DEFAULT 'pending'::character varying,
  CONSTRAINT salons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scheduled_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  client_id uuid,
  visit_id uuid,
  template_id uuid,
  phone_number character varying NOT NULL,
  message_content text NOT NULL,
  scheduled_for timestamp with time zone NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  whatsapp_message_id character varying,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  failed_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scheduled_messages_pkey PRIMARY KEY (id),
  CONSTRAINT scheduled_messages_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT scheduled_messages_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT scheduled_messages_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT scheduled_messages_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.message_templates(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  name character varying NOT NULL,
  description text,
  price numeric NOT NULL,
  duration_minutes integer DEFAULT 30,
  category character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);
CREATE TABLE public.sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  staff_id uuid NOT NULL,
  salon_id uuid NOT NULL,
  token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id),
  CONSTRAINT sessions_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);
CREATE TABLE public.staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  name character varying NOT NULL,
  phone character varying NOT NULL,
  email character varying,
  role character varying DEFAULT 'stylist'::character varying,
  is_active boolean DEFAULT true,
  daily_sales_target numeric,
  daily_sales numeric DEFAULT 0,
  commission_rate numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pin_hash character varying,
  password_hash character varying,
  last_login timestamp with time zone,
  CONSTRAINT staff_pkey PRIMARY KEY (id),
  CONSTRAINT staff_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id)
);
CREATE TABLE public.staff_performance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  staff_id uuid,
  period_start date NOT NULL,
  period_end date NOT NULL,
  total_services integer DEFAULT 0,
  total_clients integer DEFAULT 0,
  avg_rating numeric,
  five_star_count integer DEFAULT 0,
  four_star_count integer DEFAULT 0,
  three_star_count integer DEFAULT 0,
  two_star_count integer DEFAULT 0,
  one_star_count integer DEFAULT 0,
  total_complaints integer DEFAULT 0,
  complaints_resolved integer DEFAULT 0,
  would_recommend_percentage numeric,
  recovery_success_count integer DEFAULT 0,
  referrals_generated integer DEFAULT 0,
  performance_score numeric,
  rank integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_performance_pkey PRIMARY KEY (id),
  CONSTRAINT staff_performance_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT staff_performance_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id)
);
CREATE TABLE public.visit_services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  visit_id uuid,
  service_id uuid,
  quantity integer DEFAULT 1,
  price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  unit_price numeric NOT NULL,
  CONSTRAINT visit_services_pkey PRIMARY KEY (id),
  CONSTRAINT visit_services_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT visit_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id)
);
CREATE TABLE public.visits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  client_id uuid,
  staff_id uuid,
  receipt_number character varying NOT NULL UNIQUE,
  total_amount numeric NOT NULL,
  payment_method character varying NOT NULL,
  payment_status character varying DEFAULT 'pending'::character varying,
  transaction_id character varying,
  points_earned integer DEFAULT 0,
  points_redeemed integer DEFAULT 0,
  whatsapp_sent boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visits_pkey PRIMARY KEY (id),
  CONSTRAINT visits_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT visits_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT visits_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(id)
);
CREATE TABLE public.whatsapp_messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  salon_id uuid,
  visit_id uuid,
  client_id uuid,
  phone_number character varying NOT NULL,
  message text NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  message_id character varying,
  error text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  template_id uuid,
  scheduled_message_id uuid,
  delivery_status character varying DEFAULT 'pending'::character varying,
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  CONSTRAINT whatsapp_messages_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_messages_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.message_templates(id),
  CONSTRAINT whatsapp_messages_salon_id_fkey FOREIGN KEY (salon_id) REFERENCES public.salons(id),
  CONSTRAINT whatsapp_messages_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT whatsapp_messages_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT whatsapp_messages_scheduled_message_id_fkey FOREIGN KEY (scheduled_message_id) REFERENCES public.scheduled_messages(id)
);
CREATE TABLE public.whatsapp_webhooks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  webhook_id character varying,
  message_id character varying,
  status character varying,
  timestamp timestamp with time zone,
  raw_data jsonb,
  processed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT whatsapp_webhooks_pkey PRIMARY KEY (id)
);